### ISSUE TITLE
Permissions documentation is wrong for mac

### ISSUE THREAD

**Issue by betovarg** [ManatiCR/docker-grav#3]
this is what we have in the readme.md:

> chmod o+w docroot/user/config
> chmod o+w -R docroot/cache
> chmod o+w -R docroot/logs
> chmod o+w -R docroot/images
> chmod o+w -R docroot/assets
> chmod o+w -R docroot/user/data
> chmod o+w -R docroot/backup
> chmod o+w -R docroot/tmp
> chmod o+w -R docroot/user/accounts

For macs this doesn't work, should be:
> chmod -R o+w docroot/user/accounts

Im not unix versed. Should there be platform specific options?

**Comment by kporras07** [comment]
Actually that should work for both platforms. Let me know if you want to create a PR
